**Company : Cognifront**

---

**Machine Learning Intern**

---

**Name : Neha Deo**

---

**Case Study : Solve the KNN Algorithm using the given dataset play.csv** 

---

**Objective : In this Case Study, the target variable is Play. We have to split the data into training and testing parts i.e. 80% for training and 20% for testing. Note down the output of the program for the following : 
i) Accuracy, ii) Confusion Matrix, iii) Prediction Play for feature matrix : [1,2,2,1]**

---

**1] Importing Library and Acquire the Data**

In [ ]:
import pandas as pd

df = pd.read_csv("/content/play.csv")

**Printing First 5 Records**

In [ ]:
df.head()

outlook temperature humidity  windy play
0  overcast         hot     high  False  yes
1  overcast        cool   normal   True  yes
2  overcast        mild     high   True  yes
3  overcast         hot   normal  False  yes
4     rainy        mild     high  False  yes

**Printing Last 5 Records**

In [ ]:
df.tail()

outlook temperature humidity  windy play
9    sunny         hot     high  False   no
10   sunny         hot     high   True   no
11   sunny        mild     high  False   no
12   sunny        cool   normal  False  yes
13   sunny        mild   normal   True  yes

**Spliting data into Training(X) and Testing(y) parts**

In [ ]:
X = df.drop('play', axis = 1)

y = df['play']

**Printing First 5 Records of Training Data**

In [ ]:
X.head()

outlook temperature humidity  windy
0  overcast         hot     high  False
1  overcast        cool   normal   True
2  overcast        mild     high   True
3  overcast         hot   normal  False
4     rainy        mild     high  False

**Printing First 5 Records of Testing Data**

In [ ]:
y.head()

0    yes
1    yes
2    yes
3    yes
4    yes
Name: play, dtype: object

**2] Preprocess the Data**

In [ ]:
# Applying Label Encoder 

from sklearn.preprocessing import LabelEncoder
Encoder_X = LabelEncoder() 
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])

X.head()

outlook  temperature  humidity  windy
0        0            1         0      0
1        0            0         1      1
2        0            2         0      1
3        0            1         1      0
4        1            2         0      0

In [ ]:
Encoder_y=LabelEncoder()
y = Encoder_y.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1])

In [ ]:
print(type(X))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [ ]:
# Gives Statistical summary of the dataset

df.describe

<bound method NDFrame.describe of      outlook temperature humidity  windy play
0   overcast         hot     high  False  yes
1   overcast        cool   normal   True  yes
2   overcast        mild     high   True  yes
3   overcast         hot   normal  False  yes
4      rainy        mild     high  False  yes
5      rainy        cool   normal  False  yes
6      rainy        cool   normal   True   no
7      rainy        mild   normal  False  yes
8      rainy        mild     high   True   no
9      sunny         hot     high  False   no
10     sunny         hot     high   True   no
11     sunny        mild     high  False   no
12     sunny        cool   normal  False  yes
13     sunny        mild   normal   True  yes>

**Divide data into Train and Test**

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

**3] Train the Model**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
my_model = KNeighborsClassifier(n_neighbors=1)
result = my_model.fit(X_train,y_train)

**4] Test the Model**

In [ ]:
predictions = result.predict(X_test)
predictions

array([0, 1, 1])

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

confusion_matrix(y_test,predictions)

array([[1, 1],
       [0, 1]])

**Measuring Accuracy**

In [ ]:
from sklearn import metrics

print("Accuracy : ", metrics.accuracy_score(y_test, predictions))

Accuracy :  0.6666666666666666


**5] Deployment**

In [ ]:
pred_new = result.predict([[0,1,1,0]])
pred_new

array([1])

In [ ]:
pred_new = result.predict([[1,2,1,1]])
pred_new

array([0])

In [ ]:
pred_new = result.predict([[1,2,2,1]])
pred_new

array([1])